//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myTestDBEntities : DbContext
    {
        public myTestDBEntities()
            : base("name=myTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<tblAnswer> tblAnswers { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustPaymentTerm> tblCustPaymentTerms { get; set; }
        public virtual DbSet<tblCustRoute> tblCustRoutes { get; set; }
        public virtual DbSet<tblInvoiceHistory> tblInvoiceHistories { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
        public virtual DbSet<tblItemPromoGroup> tblItemPromoGroups { get; set; }
        public virtual DbSet<tblItemType> tblItemTypes { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblOrderHistory> tblOrderHistories { get; set; }
        public virtual DbSet<tblProductGroup> tblProductGroups { get; set; }
        public virtual DbSet<tblQuestionMaster> tblQuestionMasters { get; set; }
        public virtual DbSet<tblQuestionType> tblQuestionTypes { get; set; }
        public virtual DbSet<tblReturn> tblReturns { get; set; }
        public virtual DbSet<tblReturnType> tblReturnTypes { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblTropicalUser> tblTropicalUsers { get; set; }
        public virtual DbSet<tblTropicalUserRole> tblTropicalUserRoles { get; set; }
        public virtual DbSet<tblCollection> tblCollections { get; set; }
        public virtual DbSet<tblCustPaymentType> tblCustPaymentTypes { get; set; }
        public virtual DbSet<tblMesssage> tblMesssages { get; set; }
        public virtual DbSet<tblPriceGroup> tblPriceGroups { get; set; }
        public virtual DbSet<tblUserLogin> tblUserLogins { get; set; }
    }
}
