//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int CustID { get; set; }
        public Nullable<int> CustNumber { get; set; }
        public string CustName { get; set; }
        public string CustOfficeAddress1 { get; set; }
        public string CustOfficeAddress2 { get; set; }
        public string CustOfficeCity { get; set; }
        public string CustOfficeState { get; set; }
        public Nullable<int> CustOfficeZip { get; set; }
        public string CustPhoneNumber { get; set; }
        public string CustFaxNumber { get; set; }
        public Nullable<int> CustRouteNumber { get; set; }
        public Nullable<int> CustSalesRepNumber { get; set; }
        public string CustOrderEntryContactName { get; set; }
        public Nullable<int> CustPromoGroup { get; set; }
        public Nullable<int> CustPriceGroup { get; set; }
        public Nullable<int> CustPaymentTermsCode { get; set; }
        public Nullable<int> CustPaymentType { get; set; }
        public string CustBillingAddress1 { get; set; }
        public string CustBillingAddress2 { get; set; }
        public string CustBillingCity { get; set; }
        public string CustBillingState { get; set; }
        public Nullable<int> CustBillingZip { get; set; }
        public string CustRouteVisitWeekDay { get; set; }
        public Nullable<int> CustSequence { get; set; }
    }
}
