//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public int ItemID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string ItemShortDescription { get; set; }
        public string ItemDescription { get; set; }
        public string ItemUPC { get; set; }
        public Nullable<int> ItemShelfLife { get; set; }
        public string ItemReturnAllowedFlag { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<int> ItemUnits { get; set; }
        public Nullable<decimal> ItemWeights { get; set; }
        public Nullable<int> ItemPriceGroup { get; set; }
        public Nullable<int> ItemProductGroup { get; set; }
        public Nullable<int> ItemPromoGroup { get; set; }
        public string PrePrice { get; set; }
    }
}
