//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemPromoGroup
    {
        public int ItemPromoGroupID { get; set; }
        public Nullable<int> ItemPromoGroupNumber { get; set; }
        public string ItemPromoGroupDescription { get; set; }
    }
}
