//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMesssage
    {
        public int MessageID { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<int> MessageAssignRouteNumber { get; set; }
        public string MessageAllFlag { get; set; }
        public Nullable<int> MessageAssignUserID { get; set; }
        public Nullable<System.DateTime> MessageDateAndTime { get; set; }
        public Nullable<int> MessageCreatedByUser { get; set; }
    }
}
