//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderID { get; set; }
        public string OrderTrackingNumber { get; set; }
        public Nullable<int> OrderRouteNumber { get; set; }
        public Nullable<int> OrderCustomerNumber { get; set; }
        public string OrderGroupNumber { get; set; }
        public Nullable<int> OrderCaseNumbers { get; set; }
        public Nullable<int> OrderItemNumber { get; set; }
        public Nullable<decimal> OrderPromoNumber { get; set; }
        public Nullable<int> OrderItemQty { get; set; }
        public Nullable<decimal> ItemUnitPrice { get; set; }
        public Nullable<decimal> ItemTotalPrice { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string UserID { get; set; }
        public string TabletID { get; set; }
        public Nullable<System.DateTime> DataSyncDateTime { get; set; }
        public Nullable<int> OrderConfirmFlag { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<decimal> PerPoundItemsWeight { get; set; }
    }
}
