//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderHistory
    {
        public int OrderID { get; set; }
        public int OrderCustomerNumber { get; set; }
        public Nullable<int> OrderItemNumber { get; set; }
        public Nullable<System.DateTime> OrderDate1 { get; set; }
        public Nullable<decimal> OrderItemQty1 { get; set; }
        public Nullable<System.DateTime> OrderDate2 { get; set; }
        public Nullable<decimal> OrderItemQty2 { get; set; }
        public Nullable<System.DateTime> OrderDate3 { get; set; }
        public decimal OrderItemQty3 { get; set; }
        public Nullable<System.DateTime> OrderDate4 { get; set; }
        public Nullable<decimal> OrderItemQty4 { get; set; }
        public Nullable<System.DateTime> OrderDate5 { get; set; }
        public Nullable<decimal> OrderItemQty5 { get; set; }
        public Nullable<System.DateTime> OrderDate6 { get; set; }
        public Nullable<decimal> OrderItemQty6 { get; set; }
    }
}
