//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductGroup
    {
        public int ItemProductGroupID { get; set; }
        public Nullable<int> ItemProductGroupNumber { get; set; }
        public string ItemProductGroupDescription { get; set; }
    }
}
