//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionMaster
    {
        public int QuestionID { get; set; }
        public string QuestionDesc { get; set; }
        public Nullable<int> QuestionTypeID { get; set; }
        public string QuesType { get; set; }
        public string ValidationType { get; set; }
    }
}
