//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public int State_ID { get; set; }
        public string State_Abbr { get; set; }
        public string State_Description { get; set; }
        public Nullable<int> Country_ID { get; set; }
    }
}
