//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTropicalUserRole
    {
        public int RoleID { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<int> RoleCreatedBy { get; set; }
        public Nullable<System.DateTime> RoleCreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
